<?xml version="1.0" encoding="utf-8"?><Database Name="otomasyon" Class="DATABASEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ABDUSSAMED\SQLEXPRESS;Initial Catalog=otomasyon;Integrated Security=True" SettingsObjectName="otomasyon_proje_uygulması.Properties.Settings" SettingsPropertyName="otomasyonConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_STOKLAR" Member="TBL_STOKLARs">
    <Type Name="TBL_STOKLAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STOKBARKOD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STOKKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STOKADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STOKBİRİM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STOKALISFİYAT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKSATISFİYAT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKALISKDV" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKSATISKDV" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKGRUPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKRESIM" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="STOKSAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKSAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STOKEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STOKGRUPLARI" Member="TBL_STOKGRUPLARIs">
    <Type Name="TBL_STOKGRUPLARI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GRUPADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GRUPKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GRUPSAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRUPSAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GRUPEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRUPEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CAGRIGRUPLARI" Member="TBL_CAGRIGRUPLARIs">
    <Type Name="TBL_CAGRIGRUPLARI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GRUPADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GRUPKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARILER" Member="TBL_CARILERs">
    <Type Name="TBL_CARILER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CARIKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CARIADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VERGİDAIRESI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VERGINO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GRUPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ULKE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SEHIR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ILCE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADRES" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TELEFON1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TELEFON2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FAX1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FAX2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WEBADRES" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MAILINFO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="YETKILI1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YETKILIEMAIL1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="YETKILI2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YETKILIEMAIL2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARIHAREKETLERI" Member="TBL_CARIHAREKETLERIs">
    <Type Name="TBL_CARIHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BORC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ALACAK" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIPI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KASAHAREKETLERİ" Member="TBL_KASAHAREKETLERİs">
    <Type Name="TBL_KASAHAREKETLERİ">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GCKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KASALAR" Member="TBL_KASALARs">
    <Type Name="TBL_KASALAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KASAKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASADURUM" Member="VW_KASADURUMs">
    <Type Name="VW_KASADURUM">
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASAHAREKETLERI" Member="VW_KASAHAREKETLERIs">
    <Type Name="VW_KASAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KASAKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CARIKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CARIADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASALISTESI" Member="VW_KASALISTESIs">
    <Type Name="VW_KASALISTESI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KASAKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKALAR" Member="TBL_BANKALARs">
    <Type Name="TBL_BANKALAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HESAPNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BANKAADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HESAPADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ŞUBE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADRES" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TEMSILCI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEMSILCIEMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKAHAREKETLERI" Member="TBL_BANKAHAREKETLERIs">
    <Type Name="TBL_BANKAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BANKAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKALISTESI" Member="VW_BANKALISTESIs">
    <Type Name="VW_BANKALISTESI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HESAPNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BANKAADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HESAPADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKAHAREKETLERI" Member="VW_BANKAHAREKETLERIs">
    <Type Name="VW_BANKAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BANKAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKADURUM" Member="VW_BANKADURUMs">
    <Type Name="VW_BANKADURUM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GCKODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KULLANICILAR" Member="TBL_KULLANICILARs">
    <Type Name="TBL_KULLANICILAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KULLANICI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SIFRE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISIM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOYISIM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AKTIF" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KODU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LASTLOGIN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>